name: Compose + Podman Test

on:
  workflow_dispatch:

jobs:
  merge-compose:
    name: Merge compose+podman into ${{ matrix.upstream_branch }}
    strategy:
      matrix:
        upstream_branch: [main, dev]
    uses: ./.github/workflows/merge-prs-workflow.yml
    with:
      pr_numbers: '485,1135'
      upstream_repo: nextlevelbuilder/goclaw
      upstream_branch: ${{ matrix.upstream_branch }}
      output_repo: keithy/goclaw
      branch_name: ${{ matrix.upstream_branch }}+compose-podman
    secrets: inherit
